//"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./css/globals.css";
import {Flowbite, ThemeModeScript} from "flowbite-react";
import customTheme from "@/utils/theme/custom-theme";
import {CustomizerContextProvider} from "@/app/context/CustomizerContext";
import React from "react";
import {ReduxProvider} from "@/redux/provider";
import {NextIntlClientProvider} from 'next-intl';

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Application Akuaba",
  //description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        <ThemeModeScript />
          <title>Application Akuaba</title>
      </head>
      <body className={`${inter.className}`} suppressHydrationWarning>
          <NextIntlClientProvider>
              <ReduxProvider>
                  <Flowbite theme={{theme: customTheme}}>
                      <CustomizerContextProvider>
                          {children}
                      </CustomizerContextProvider>
                  </Flowbite>
              </ReduxProvider>
          </NextIntlClientProvider>
      </body>
    </html>
  );
}
